import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Axis Engine module boundaries', () => {
  it('keeps runtime contracts in shared and pure orchestration policies in main', async () => {
    const contract = await source('shared/axis-engine-contracts.ts')
    const scheduler = await source('main/services/axis-dag-scheduler.ts')
    const budgetGuard = await source('main/services/axis-budget-guard.ts')
    const coordinator = await source('main/services/axis-shadow-run-coordinator.ts')
    const evaluator = await source('main/services/axis-complexity-evaluator.ts')
    const decomposer = await source('main/services/axis-task-decomposer.ts')
    const planningModel = await source('main/services/axis-planning-model.ts')
    const providerPlanningModel = await source('main/services/ai-sdk-axis-planning-model.ts')
    const providerPivotModel = await source('main/services/ai-sdk-axis-pivot-model.ts')
    const structuredModelRuntime = await source('main/services/axis-structured-model-runtime.ts')
    const replanCoordinator = await source('main/services/axis-replan-coordinator.ts')
    const planLineageRegistry = await source('main/services/axis-plan-lineage-registry.ts')
    const pivotCoordinator = await source('main/services/axis-pivot-coordinator.ts')
    const pivotDecisionRegistry = await source('main/services/axis-pivot-decision-registry.ts')
    const pivotModel = await source('main/services/axis-pivot-model.ts')
    const pivotPolicy = await source('main/services/axis-pivot-policy.ts')
    const runState = await source('shared/axis-run-state.ts')
    const runStateRegistry = await source('main/services/axis-run-state-registry.ts')
    const dryRunCoordinator = await source('main/services/axis-dry-run-coordinator.ts')
    const taskExecutor = await source('main/services/axis-task-executor.ts')
    const executionQuality = await source('main/services/axis-execution-quality.ts')
    const executionAuthority = await source('main/services/axis-execution-authority.ts')
    const fakeMutatingExecutor = await source('main/services/axis-fake-mutating-executor.ts')
    const permissionGrantCollector = await source('main/services/axis-permission-grant-collector.ts')
    const permissionManagerPort = await source('main/services/axis-permission-manager-port.ts')
    const checkpointReceiptIssuer = await source('main/services/axis-checkpoint-receipt-issuer.ts')
    const guardedFakeExecution = await source('main/services/axis-guarded-fake-execution.ts')
    const guardedSafeWrite = await source('main/services/axis-guarded-safe-write.ts')
    const guardedTransaction = await source('main/services/axis-guarded-transaction.ts')
    const safeWriteWorker = await source('main/services/axis-safe-write-worker.ts')
    const gateRunner = await source('main/services/axis-gate-runner.ts')
    const gateEvidence = await source('main/services/axis-gate-evidence-registry.ts')
    const transactionJournal = await source('main/services/axis-execution-transaction-journal.ts')
    const physicalRollback = await source('main/services/axis-physical-rollback-executor.ts')
    const executionRecovery = await source('main/services/axis-execution-recovery.ts')
    const guardedIpcRuntime = await source('main/services/axis-guarded-ipc-runtime.ts')
    const ipcHandlers = await source('main/ipc-handlers.ts')

    expect(contract).not.toMatch(/from ['"].*\/(main|renderer)\//)
    expect(scheduler).toContain("from '../../shared/axis-engine-contracts'")
    expect(budgetGuard).toContain("from '../../shared/axis-engine-contracts'")
    expect(`${scheduler}\n${budgetGuard}\n${coordinator}\n${evaluator}\n${decomposer}\n${planningModel}\n${providerPlanningModel}\n${providerPivotModel}\n${structuredModelRuntime}`)
      .not.toMatch(/shared_data|AgentRuntime|AgentToolExecutor|BrowserWindow|ipcMain|renderer\//)
    expect(planningModel).toContain('cannot execute tools')
    expect(providerPlanningModel).toMatch(/Never execute tools/)
    expect(providerPivotModel).toMatch(/Never execute tools/)
    expect(`${replanCoordinator}\n${planLineageRegistry}`)
      .not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|BrowserWindow|ipcMain|renderer\//)
    expect(`${pivotCoordinator}\n${pivotDecisionRegistry}\n${pivotModel}\n${pivotPolicy}`)
      .not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|BrowserWindow|ipcMain|renderer\//)
    expect(pivotModel).toContain('cannot mutate run state or invoke tools')
    expect(runState).not.toMatch(/from ['"].*\/(main|renderer)\//)
    expect(runStateRegistry).not.toMatch(/AgentRuntime|AgentToolExecutor|term:run|fs:safe-write/)
    expect(`${dryRunCoordinator}\n${taskExecutor}\n${executionQuality}`).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|term:run|fs:safe-write/)
    expect(taskExecutor).toContain('without invoking tools, commands, or file operations')
    expect(executionQuality).toContain("authority: 'simulation'")
    expect(`${executionAuthority}\n${fakeMutatingExecutor}`).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|writeFile|unlink|term:run|fs:safe-write/)
    expect(fakeMutatingExecutor).toContain("mode: 'fake-mutation'")
    expect(permissionGrantCollector).not.toMatch(/AgentRuntime|AgentToolExecutor|BrowserWindow|ipcMain|renderer\//)
    expect(permissionManagerPort).toContain('permissions.requestDetailed')
    expect(permissionManagerPort).not.toMatch(/AgentRuntime|AgentToolExecutor|BrowserWindow|ipcMain|renderer\//)
    expect(checkpointReceiptIssuer).not.toMatch(/AgentRuntime|AgentToolExecutor|SafeFileWriter|writeFile|unlink|ipcMain|renderer\//)
    expect(guardedFakeExecution).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|writeFile|unlink|ipcMain|renderer\//)
    expect(guardedSafeWrite).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|writeFile|unlink|ipcMain|renderer\//)
    expect(guardedSafeWrite).toMatch(/AxisFileLeasePortFactory/)
    expect(guardedSafeWrite).toMatch(/AxisFileFingerprintPortFactory/)
    expect(guardedSafeWrite).not.toMatch(/SqliteAxisFileLeaseStore|AxisExternalFileFingerprintAdapter/)
    expect(guardedSafeWrite.indexOf('this.feature.isRealExecutionEnabled()')).toBeLessThan(guardedSafeWrite.indexOf('this.grantCollector.collect'))
    expect(guardedSafeWrite.indexOf('recordPrecommit')).toBeLessThan(guardedSafeWrite.indexOf('completedTransaction = this.guardedTransaction.complete(transaction)'))
    expect(guardedSafeWrite.indexOf('completedTransaction = this.guardedTransaction.complete(transaction)')).toBeLessThan(guardedSafeWrite.indexOf('completionEvidence: completionEvidence('))
    expect(guardedTransaction).not.toMatch(/node:fs|better-sqlite3|AgentRuntime|AgentToolExecutor|BrowserWindow|ipcMain|renderer\//)
    expect(safeWriteWorker).toContain('writeTextFile')
    expect(safeWriteWorker).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|BrowserWindow|ipcMain|renderer\//)
    expect(safeWriteWorker).not.toMatch(/AxisFileLeasePortFactory|AxisFileFingerprintPortFactory|AxisFileLeaseAdminPort|node:fs/)
    expect(gateRunner).not.toMatch(/node:child_process|CommandRunner|AgentRuntime|AgentToolExecutor|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|BrowserWindow|ipcMain|renderer\//)
    expect(gateEvidence).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|FileCheckpointStore|BrowserWindow|ipcMain|renderer\//)
    expect(transactionJournal).not.toMatch(/AgentRuntime|AgentToolExecutor|BrowserWindow|ipcMain|renderer\//)
    expect(executionRecovery).not.toMatch(/node:fs|better-sqlite3|AgentRuntime|AgentToolExecutor|BrowserWindow|ipcMain|renderer\//)
    expect(physicalRollback).not.toMatch(/AgentRuntime|AgentToolExecutor|CommandRunner|TerminalManager|SafeFileWriter|PermissionManager|BrowserWindow|ipcMain|renderer\//)
    expect(physicalRollback).toMatch(/unlink|checkpoints\.restore/)
    expect(guardedIpcRuntime).toMatch(/createAxisProductionGuardedRuntime/)
    expect(guardedIpcRuntime).toMatch(/AxisGuardedSafeWriteSubmissionService/)
    expect(guardedIpcRuntime).not.toMatch(/BrowserWindow|ipcMain|renderer\//)
    expect(ipcHandlers).not.toMatch(/AxisGuardedFakeExecutionHarness|AxisGuardedSafeWriteHarness|AxisSafeWriteWorker|AxisGateRunner|AxisGateEvidenceRegistry|isRealExecutionEnabled|AxisMainPermissionGrantCollector|AxisCheckpointReceiptIssuer|AxisPhysicalRollbackExecutor|AxisExecutionRecoveryCoordinator|AxisReplanCoordinator|AxisPlanLineageRegistry|AxisPivotCoordinator|AxisPivotDecisionRegistry/)
  })

  it('encodes one-layer workers and hard limits as executable contracts', async () => {
    const contract = await source('shared/axis-engine-contracts.ts')

    expect(contract).toContain('spawnDepth: z.literal(1)')
    expect(contract).toContain('maxWorkers: z.number().int().min(1).max(8)')
    expect(contract).toContain("'gate-cycle-limit'")
    expect(contract).toContain("mode: z.literal('shadow')")
    expect(contract).toContain("'dedicated-fixer'")
    expect(contract).toContain("'discard'")
  })
})

function source(relativePath: string): Promise<string> {
  return readFile(path.resolve('src', relativePath), 'utf8')
}
